<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en-gb" lang="en-gb">
<head>
  <link href="http://gmpg.org/xfn/11" rel="profile">
  <meta http-equiv="content-type" content="text/html; charset=utf-8">
  <meta name="generator" content="Hugo 0.25.1" />

  
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1">

  
  <title>Django Bug? &middot; Mildly Skilled</title>
  

  
  <link rel="stylesheet" href="css/print.css" media="print">
  <link rel="stylesheet" href="css/poole.css">
  <link rel="stylesheet" href="css/syntax.css">
  <link rel="stylesheet" href="css/hyde.css">
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=PT+Sans:400,400italic,700|Abril+Fatface">

  
  <link rel="apple-touch-icon-precomposed" sizes="144x144" href="../../apple-touch-icon-144-precomposed.png">
  <link rel="shortcut icon" href="../../favicon.png">

  
  <link href="" rel="alternate" type="application/rss+xml" title="Mildly Skilled" />
</head>

<body class=" layout-reverse">
  <div class="sidebar">
  <div class="container sidebar-sticky">
    <div class="sidebar-about">
      <a href=""><h1>Mildly Skilled</h1></a>
      <p class="lead">
       Software development for the mildly skilled. A blog maintained by Kwabena Aning, whose opinions are his own :/ 
      </p>
    </div>

    <ul class="sidebar-nav">
      <li><a href="">Home</a> </li>
      
    </ul>

    <p>&copy; 2017. All rights reserved. </p>
  </div>
</div>


  <div class="content container">
    <div class="post">
      <h1>Django Bug?</h1>
      <span class="post-date">Thu, Oct 23, 2014</span>
      <p>After spending hours trying to debug why my settings file was not being found I stumbled across this</p>

<p>I&rsquo;ve found the answer to my question.</p>

<p>If you&rsquo;ve got an error in your settings, manage.py will swallow the exception and report as if the command does not exist.
This lead me down the path of incorrectly assuming my python path or venv environment was messed up.
If you want to diagnose this issue, run&hellip;</p>

<p>python app/manage.py help</p>

<p>&hellip; and it will show the exception. This, of course, was what was recommended by the django shell after it had told me that the command was not found.</p>

<p>This is clearly a bug in Django 1.4. It seems to me, an Exception should be reported regardless of what management command you run.</p>

<p><a href="http://stackoverflow.com/questions/14885299/django-1-4-unknown-command-runserver">http://stackoverflow.com/questions/14885299/django-1-4-unknown-command-runserver</a></p>

    </div>

			
		</div>

</body>
</html>